---
- hosts: all
  become: true
  ignore_errors: yes
  gather_facts: yes
  #become_user: root

  tasks:
      - name: Create a file
        file:
           path: /tmp/playbookfile
           mode: '0755'
           state: touch
           tags:
              - file 

      - name: Create a directory
        file:
           path: /tmp/dir
           mode: '0700'
           state: directory
           tags:


      - name: Create a group
        group:
           name: security
           state: present

      - name: Create user Harvey
        user:
           comment: Harvey Admin
           shell: /bin/bash
           group: security
           name: harvey
        when: ansible_os_family == "Iphone" or anisble_processor_nproc > 2

      - name: Check uptime
        command: uptime
      - name: Check the date
        shell: cat /etc/passwd | grep harvey
