---
- hosts: all
  become: true
  gather_facts: no
  vars_files: 
    - vars.yaml
  tasks:
    - name: Copy config file
      template:
        dest: /tmp/apache.conf
        src: /home/ec2-user/ansible-dev/apache.j2