---
- name: Install apache
  yum: 
    name: "{{ apache_pkg }}"
    state: "{{ pkg_state }}"

- name: Start Daeom
  service:
    name: "{{ service_name }}"
    state: "{{ serivce_state }}"
- name: Create a file
  file:
    path: "{{ file_path }}"
    state: "{{ file_state }}"
- name: File content
  lineinfile:
    path: "{{ file_path }}"
    line: "{{ content }}"